# Generated by Django 4.1.3 on 2022-12-18 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode='name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Direction_Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode='code', max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('date_create', models.DateField(default=django.utils.timezone.now)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_prog', to='indplan.direction_subject')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edprog_group', to='indplan.educationprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique='shortname')),
            ],
            options={
                'ordering': ('fullname', 'shortname'),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='teachers/profile_pics')),
                ('teacher_ID', models.CharField(max_length=20, unique=True)),
                ('academic_rank', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant professor', 'Assistant professor'), ('Associate professor', 'Associate professor'), ('Professor', 'Professor'), ('Professor emeritus', 'Professor emeritus')], max_length=100)),
                ('teacher_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='indplan.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['teacher_ID'],
                'unique_together': {('teacher_ID', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
                ('credit', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='indplan.category_subject')),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_subjects', to='indplan.department')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction', to='indplan.direction_subject')),
                ('teacherId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_subjects', to='indplan.teacher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='students/profile_pics')),
                ('student_ID', models.CharField(max_length=20, unique=True)),
                ('student_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('year_entered', models.DateField(default=django.utils.timezone.now)),
                ('group_st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='indplan.groupstudent')),
                ('user_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_ID'],
                'unique_together': {('user_student', 'group_st')},
            },
        ),
        migrations.CreateModel(
            name='IndividualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indplan.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indplan.subject')),
            ],
            options={
                'ordering': ['semestr'],
            },
        ),
        migrations.AddField(
            model_name='groupstudent',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_groups', to='indplan.institute'),
        ),
        migrations.CreateModel(
            name='EducationProgramMainSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationProg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indplan.educationprogram')),
                ('mainsubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indplan.subject')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_departments', to='indplan.institute'),
        ),
    ]
