# Generated by Django 4.1.3 on 2022-12-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indplan', '0005_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogrammainsubject',
            name='code_subject',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='EducationProgramSelectiveSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_subject', models.CharField(max_length=10, null=True)),
                ('number_from_two', models.PositiveSmallIntegerField(default=1)),
                ('educationProg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indplan.educationprogram')),
                ('selectivesubject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='indplan.subject')),
            ],
        ),
    ]
