# Generated by Django 4.1.3 on 2022-12-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indplan', '0007_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogrammainsubject',
            name='semestr',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='educationprogramselectivesubject',
            name='semestr',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
