# Generated by Django 4.1.3 on 2022-12-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indplan', '0008_educationprogrammainsubject_semestr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualplan',
            name='code_subject',
            field=models.CharField(default='ВК07', max_length=10),
        ),
    ]
