# Generated by Django 4.1.3 on 2022-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indplan', '0009_individualplan_code_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstudent',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
