# Generated by Django 4.1.3 on 2022-12-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indplan', '0010_alter_groupstudent_slug_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_subject',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
