# Generated by Django 4.1.3 on 2022-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indplan', '0011_category_subject_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_subject',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
